.\" man page create by R# package system.
.TH TCP 1 2000-1月 "port_in_used" "port_in_used"
.SH NAME
port_in_used \- get a list of tcp port in used
.SH SYNOPSIS
\fIport_in_used(\fBverbose\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
get a list of tcp port in used
.PP
.SH SEE ALSO
tcp
.SH FILES
.PP
Darwinism.dll
.PP
