.\" man page create by R# package system.
.TH MEMORY_QUERY 1 2000-1月 "between" "between"
.SH NAME
between \- value between a given range?
.SH SYNOPSIS
\fIbetween(\fBname\fR as string, 
\fBrange\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
value between a given range?
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- -. 
.PP
.PP
\fBrange\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
memory_query
.SH FILES
.PP
Darwinism.dll
.PP
