.\" man page create by R# package system.
.TH MEMORY_QUERY 1 2000-Jan "fulltext" "fulltext"
.SH NAME
fulltext \- set full text search index on data fields
.SH SYNOPSIS
\fIfulltext(\fBx\fR as <generic> MemoryIndex, 
\fBfields\fR as string);\fR
.SH DESCRIPTION
.PP
set full text search index on data fields
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBfields\fB \fR\- -. 
.PP
.SH SEE ALSO
memory_query
.SH FILES
.PP
Darwinism.dll
.PP
