.\" man page create by R# package system.
.TH MEMORY_QUERY 1 2000-Jan "hashindex" "hashindex"
.SH NAME
hashindex \- set hash term search index on data fields
.SH SYNOPSIS
\fIhashindex(\fBx\fR as <generic> MemoryTable, 
\fBfields\fR as string);\fR
.SH DESCRIPTION
.PP
set hash term search index on data fields
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBfields\fB \fR\- -. 
.PP
.SH SEE ALSO
memory_query
.SH FILES
.PP
Darwinism.dll
.PP
