.\" man page create by R# package system.
.TH MEMORY_QUERY 1 2000-Jan "load" "load"
.SH NAME
load \- load in-memory table
.SH SYNOPSIS
\fIload(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load in-memory table
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a dataframe object, or the file resource to a csv dataframe file. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
memory_query
.SH FILES
.PP
Darwinism.dll
.PP
