.\" man page create by R# package system.
.TH MEMORY_QUERY 1 2000-1月 "match_against" "match_against"
.SH NAME
match_against \- create a full text search filter
.SH SYNOPSIS
\fImatch_against(\fBname\fR as string, 
\fBtext\fR as string, 
\fBboolean_mode\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
create a full text search filter
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- -. 
.PP
.PP
\fBtext\fB \fR\- -. 
.PP
.PP
\fBboolean_mode\fB \fR\- 
 set this parameter will use the levenshtein similarity matches method for index search
. 
.PP
.SH SEE ALSO
memory_query
.SH FILES
.PP
Darwinism.dll
.PP
