.\" man page create by R# package system.
.TH MEMORY_QUERY 1 2000-1月 "valueindex" "valueindex"
.SH NAME
valueindex \- set value range search index on data fields
.SH SYNOPSIS
\fIvalueindex(\fBx\fR as <generic> MemoryIndex, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set value range search index on data fields
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBfields\fB \fR\- 
 a collection of the key-value tuples for create index fields,
 field = type, type should be one of the enum terms: number,integer,date
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
memory_query
.SH FILES
.PP
Darwinism.dll
.PP
