.\" man page create by R# package system.
.TH CENTOS 1 2000-Jan "check_command_exists" "check_command_exists"
.SH NAME
check_command_exists \- check command is existsed on linux system or not?
.SH SYNOPSIS
\fIcheck_command_exists(\fBcommand\fR as string, 
\fBverbose\fR as <generic> Boolean = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
check command is existsed on linux system or not?
.PP
.SH OPTIONS
.PP
\fBcommand\fB \fR\- 
 the command name
. 
.PP
.SH SEE ALSO
centos
.SH FILES
.PP
Darwinism.dll
.PP
