.\" man page create by R# package system.
.TH CENTOS 1 2000-1月 "parse_tcp" "parse_tcp"
.SH NAME
parse_tcp \- Parse the file content of file \fB/proc/net/tcp\fR
.SH SYNOPSIS
\fIparse_tcp(\fBtext\fR as string);\fR
.SH DESCRIPTION
.PP
Parse the file content of file \fB/proc/net/tcp\fR
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- -. 
.PP
.SH SEE ALSO
centos
.SH FILES
.PP
Darwinism.dll
.PP
