.TH ___CONFIG_RUNTIME_ENV 1 2025-Jan "" "Configs of the default parallel runtime environment"
.SH NAME
___config_runtime_env \- ___config_runtime_env()
.SH SYNOPSIS
\fI___config_runtime_env()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.___config_runtime_env at env.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
