.TH ___CHECK_NETSTAT 1 2025-Jun "" "Check of netstat tool is installed or not"
.SH NAME
___check_netstat \- ___check_netstat()
.SH SYNOPSIS
\fI___check_netstat()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.___check_netstat at env.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
