.TH __CALL_RSCRIPT_DOCKER 1 2024-Dec "" "A helper function for run Rscript inside a docker container"
.SH NAME
__call_rscript_docker \- __call_rscript_docker(image.id, script.code, workdir, mount,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fI__call_rscript_docker(image.id, script.code, workdir, mount,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBimage.id\fB \fR\- . 
.PP
.PP
\fBscript.code\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- . 
.PP
.PP
\fBmount\fB \fR\- . 
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__call_rscript_docker at docker.R:line 73
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
