.TH __RSCRIPT_TMP 1 2025-Mar "" "__rscript_tmp"
.SH NAME
__rscript_tmp \- __rscript_tmp(workdir)
.SH SYNOPSIS
\fI__rscript_tmp(workdir)\fR
.SH OPTIONS
.PP
\fBworkdir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__rscript_tmp at docker.R:line 53
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
