.TH CONTAINER_ID 1 2025-Aug "" "check of the script is running inside a docker container or not?"
.SH NAME
container_id \- container_id()
.SH SYNOPSIS
\fIcontainer_id()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.container_id at docker.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
