.TH CONTAINER_ID 1 2025-Nov "" "check of the script is running inside a docker container or not?"
.SH NAME
container_id \- container_id()
.SH SYNOPSIS
\fIcontainer_id()\fR
.SH VALUE
.PP
this function returns a character vector of the current
docker container id if script process is running inside a docker
container environment, or nothing if not.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.container_id at docker.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
