.TH GET_MAC_ADDRESSES 1 2025-Aug "" "Retrieve MAC Addresses of Network Interfaces"
.SH NAME
get_mac_addresses \- get_mac_addresses()
.SH SYNOPSIS
\fIget_mac_addresses()\fR
.SH DESCRIPTION
.PP
Scans system network interfaces and extracts MAC addresses, excluding loopback interfaces.
.PP
.SH VALUE
.PP
A named list where:
\itemize{
\item Names are network interface names (e.g., "eth0")
\item Values are corresponding MAC addresses (empty string if unavailable)
}
.PP
.SH EXAMPLES
.PP
#\dontrun{

macs <- get_mac_addresses()

#}
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_mac_addresses at env.R:line 148
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
