.TH HARDWARE_SIGN 1 2025-Jun "" "Generate Hardware-based Digital Signatures"
.SH NAME
hardware_sign \- hardware_sign(
    <i>salt</i> = <span style='color: brown;'><strong>''</strong></span>,
    <i>salt.bytes</i> = <span style='color: blue !important;'>NULL</span>,
    <i>verbose</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIhardware_sign(
    <i>salt</i> = <span style='color: brown;'><strong>''</strong></span>,
    <i>salt.bytes</i> = <span style='color: blue !important;'>NULL</span>,
    <i>verbose</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBsalt\fB \fR\- ''. Character string (typically user email) to add entropy to signatures.
.PP
.PP
\fBsalt.bytes\fB \fR\- NULL. 
.PP
.PP
\fBverbose\fB \fR\- FALSE. Logical. Show debug information during generation (default: FALSE).
.PP
.SH VALUE
.PP
Character vector of MD5 checksums: \itemize{ \item Length matches number of valid network interfaces \item Order corresponds to interfaces returned by get_mac_addresses() \item Each checksum incorporates hardware profile + MAC address + salt(s) }
.PP
.SH EXAMPLES
.PP
\dontrun{ signatures <- hardware_sign(salt = "user@example.com") }
.PP
.SH SEE ALSO
\code{\link{hardware_abstract}} for underlying hardware data collection
.SH FILES
.PP
SMRUCC/R#.declare_function.hardware_sign at env.R:line 195
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
