.TH HARDWARE_SIGN 1 2025-Apr "" "hardware_sign"
.SH NAME
hardware_sign \- hardware_sign(
    <i>salt</i> = <span style='color: brown;'><strong>''</strong></span>,
    <i>salt.bytes</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIhardware_sign(
    <i>salt</i> = <span style='color: brown;'><strong>''</strong></span>,
    <i>salt.bytes</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBsalt\fB \fR\- ''. 
.PP
.PP
\fBsalt.bytes\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.hardware_sign at env.R:line 79
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
