.TH HARDWARE_KEYS 1 2025-Jun "" "get and print the generated hardware keys"
.SH NAME
hardware_keys \- hardware_keys(
    <i>salt</i> = <span style='color: brown;'><strong>''</strong></span>,
    <i>salt.bytes</i> = <span style='color: blue !important;'>NULL</span>,
    <i>verbose</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIhardware_keys(
    <i>salt</i> = <span style='color: brown;'><strong>''</strong></span>,
    <i>salt.bytes</i> = <span style='color: blue !important;'>NULL</span>,
    <i>verbose</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBsalt\fB \fR\- ''. 
.PP
.PP
\fBsalt.bytes\fB \fR\- NULL. 
.PP
.PP
\fBverbose\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.hardware_keys at env.R:line 219
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
