.TH HARDWARE_ABSTRACT 1 2025-Apr "" "get platform hardware abstract report"
.SH NAME
hardware_abstract \- hardware_abstract()
.SH SYNOPSIS
\fIhardware_abstract()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.hardware_abstract at env.R:line 42
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
