.TH NO_NETSTAT_WARNING 1 2025-Jun "" "show warning message about missing ``netstat`` command"
.SH NAME
no_netstat_warning \- no_netstat_warning()
.SH SYNOPSIS
\fIno_netstat_warning()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.no_netstat_warning at env.R:line 28
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
