<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Darwinism.HPC.DistributedCluster.Host</RootNamespace>
    <ImportMicrosoftVisualBasic>false</ImportMicrosoftVisualBasic>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Host</AssemblyName>
    <AssemblyTitle>Host head node</AssemblyTitle>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\httpd\src\Flute\Flute.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\..\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\ClusterShared\ClusterShared.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
