.\" man page create by R# package system.
.TH DOCKER 1 2000-Jan "image" "image"
.SH NAME
image \- create docker image reference
.SH SYNOPSIS
\fIimage(\fBx\fR as any, 
\fBname\fR as string = \fB<NULL>\fR, 
\fBpublisher\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create docker image reference
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
