.\" man page create by R# package system.
.TH DOCKER 1 2000-Jan "rmImage" "rmImage"
.SH NAME
rmImage \- delete docker images and related containers
.SH SYNOPSIS
\fIrmImage(\fBimageId\fR as string);\fR
.SH DESCRIPTION
.PP
delete docker images and related containers
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
