.\" man page create by R# package system.
.TH DOCKER 1 2000-Jan "run" "run"
.SH NAME
run \- Run a command in a new container.(这个函数会捕捉到命令的标准输出然后以字符串的形式返回)
.SH SYNOPSIS
\fIrun(\fBcontainer\fR as any, 
\fBcommand\fR as string, 
\fBscript\fR as string = \fB<NULL>\fR, 
\fBworkdir\fR as string = \fB<NULL>\fR, 
\fBmounts\fR as <generic> Mount[] = \fB<NULL>\fR, 
\fBportForward\fR as <generic> PortForward = \fB<NULL>\fR, 
..., 
\fBshell_cmdl\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Run a command in a new container.(这个函数会捕捉到命令的标准输出然后以字符串的形式返回)
.PP
.SH OPTIONS
.PP
\fBcommand\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- 
 the commandline arguments for the shell **`command`** run inside a docker container.
. 
.PP
.PP
\fBshell_cmdl\fB \fR\- 
 this debug parameter specific that just returns the commandline for 
 run docker instead of run command and returns the std_output.
. 
.PP
.SH DETAILS
.PP
这个方法能够自定义的参数比较有限,如果需要更加复杂的使用方法,可以使用@\fBT:Darwinism.Docker.Environment\fR对象
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
