.\" man page create by R# package system.
.TH DOCKER 1 2000-Jan "stop" "stop"
.SH NAME
stop \- Stop one or more running containers
.SH SYNOPSIS
\fIstop(\fBcontainers\fR as string);\fR
.SH DESCRIPTION
.PP
Stop one or more running containers
.PP
.SH OPTIONS
.PP
\fBcontainers\fB \fR\- -. 
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
