.\" man page create by R# package system.
.TH DOCKER 1 2000-1月 "stop_container" "stop_container"
.SH NAME
stop_container \- Stop one or more running containers
.SH SYNOPSIS
\fIstop_container(\fBcontainers\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Stop one or more running containers
.PP
.SH OPTIONS
.PP
\fBcontainers\fB \fR\- -. 
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
