.\" man page create by R# package system.
.TH DOCKER 1 2000-1月 "tty" "tty"
.SH NAME
tty \- enable interactive tty device
.SH SYNOPSIS
\fItty(\fBdocker\fR as <generic> Environment, 
\fBopt\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
enable interactive tty device
.PP
.SH OPTIONS
.PP
\fBdocker\fB \fR\- -. 
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
