.\" man page create by R# package system.
.TH DOCKER 1 2000-Jan "workdir" "workdir"
.SH NAME
workdir \- set the workdir for run the command inside this new docker container
.SH SYNOPSIS
\fIworkdir(\fBdocker\fR as <generic> Environment, 
\fBdir\fR as string);\fR
.SH DESCRIPTION
.PP
set the workdir for run the command inside this new docker container
.PP
.SH OPTIONS
.PP
\fBdocker\fB \fR\- -. 
.PP
.PP
\fBdir\fB \fR\- the directory path inside the docker container.. 
.PP
.SH SEE ALSO
docker
.SH FILES
.PP
Darwinism.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
