.\" man page create by R# package system.
.TH MATH 1 2000-Jan "knn" "knn"
.SH NAME
knn \- 
.SH SYNOPSIS
\fIknn(\fBx\fR as any, 
\fBk\fR as integer = 16, 
\fBcutoff\fR as double = 0.8, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBcutoff\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function only supports the cosine similarity score function.
.PP
.SH SEE ALSO
Math
.SH FILES
.PP
Darwinism.dll
.PP
