.\" man page create by R# package system.
.TH MATH 1 2000-1月 "pearson_cor" "pearson_cor"
.SH NAME
pearson_cor \- 
.SH SYNOPSIS
\fIpearson_cor(\fBx\fR as any, 
\fBy\fR as any, 
\fBprefilter_cor\fR as double = 0.3, 
\fBprefilter_pval\fR as double = 0.05, 
\fBn_trheads\fR as integer = 8, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Math
.SH FILES
.PP
Darwinism.dll
.PP
