.\" man page create by R# package system.
.TH MATH 1 2000-1月 "write_network" "write_network"
.SH NAME
write_network \- write the correlation network
.SH SYNOPSIS
\fIwrite_network(\fBcor\fR as any, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
write the correlation network
.PP
.SH OPTIONS
.PP
\fBcor\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Math
.SH FILES
.PP
Darwinism.dll
.PP
