<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Darwinism.HPC.DistributedCluster.SlaveNode</RootNamespace>
    <ImportMicrosoftVisualBasic>false</ImportMicrosoftVisualBasic>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Node</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\ClusterShared\ClusterShared.vbproj" />
  </ItemGroup>

</Project>
