.\" man page create by R# package system.
.TH ENVIRONMENT 1 2000-Jan "set_threads" "set_threads"
.SH NAME
set_threads \- set the parallel batch threads
.SH SYNOPSIS
\fIset_threads(\fBn_threads\fR as integer);\fR
.SH DESCRIPTION
.PP
set the parallel batch threads
.PP
.SH OPTIONS
.PP
\fBn_threads\fB \fR\- -. 
.PP
.SH SEE ALSO
Environment
.SH FILES
.PP
Darwinism.dll
.PP
