.\" man page create by R# package system.
.TH ENVIRONMENT 1 2000-1月 "set_libpath" "set_libpath"
.SH NAME
set_libpath \- Set framework library directory path
.SH SYNOPSIS
\fIset_libpath(\fBlibpath\fR as string);\fR
.SH DESCRIPTION
.PP
Set framework library directory path
 
 set a directory path that contains the scibasic.net framework 
 runtime of the current parallel environment.
.PP
.SH OPTIONS
.PP
\fBlibpath\fB \fR\- -. 
.PP
.SH SEE ALSO
Environment
.SH FILES
.PP
Darwinism.dll
.PP
