<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Darwinism.HPC.DistributedCluster.Shared</RootNamespace>
    <AssemblyName>Darwinism.HPC.DistributedCluster.Shared</AssemblyName>
    <ImportMicrosoftVisualBasic>false</ImportMicrosoftVisualBasic>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
  </ItemGroup>

</Project>
