.\" man page create by R# package system.
.TH CDF 1 2000-1月 "open" "open"
.SH NAME
open \- open a connection to the netcdf file
.SH SYNOPSIS
\fIopen(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
open a connection to the netcdf file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH VALUE
.PP
the file stream id
.PP
.SH SEE ALSO
CDF
.SH FILES
.PP
Darwinism.dll
.PP
