.\" man page create by R# package system.
.TH CDF 1 2000-Jan "var_data" "var_data"
.SH NAME
var_data \- get variable data from given file
.SH SYNOPSIS
\fIvar_data(\fBnc\fR as <generic> DataReader, 
\fBname\fR as string);\fR
.SH DESCRIPTION
.PP
get variable data from given file
.PP
.SH OPTIONS
.PP
\fBnc\fB \fR\- -. 
.PP
.PP
\fBname\fB \fR\- -. 
.PP
.SH SEE ALSO
CDF
.SH FILES
.PP
Darwinism.dll
.PP
