.\" man page create by R# package system.
.TH BASH 4 2000-1月 "exec" "exec"
.SH NAME
exec \- Execute a command on remote linux server session.
.SH SYNOPSIS
\fIexec(\fBssh\fR as <generic> PuTTY, 
\fBcommand\fR as string, 
\fBarguments\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Execute a command on remote linux server session.
.PP
.SH OPTIONS
.PP
\fBssh\fB \fR\- remote linux ssh session. 
.PP
.PP
\fBcommand\fB \fR\- -. 
.PP
.PP
\fBarguments\fB \fR\- -. 
.PP
.SH SEE ALSO
bash
.SH FILES
.PP
Darwinism.dll
.PP
