.\" man page create by R# package system.
.TH BASH 4 2000-Jan "run" "run"
.SH NAME
run \- Run a script on remote linux server session.
.SH SYNOPSIS
\fIrun(\fBssh\fR as <generic> PuTTY, 
\fBscript\fR as string);\fR
.SH DESCRIPTION
.PP
Run a script on remote linux server session.
.PP
.SH OPTIONS
.PP
\fBssh\fB \fR\- remote linux ssh session. 
.PP
.PP
\fBscript\fB \fR\- -. 
.PP
.SH SEE ALSO
bash
.SH FILES
.PP
Darwinism.dll
.PP
