.\" man page create by R# package system.
.TH BASH 4 2000-1月 "ssh" "ssh"
.SH NAME
ssh \- Create a new remote linux ssh session
.SH SYNOPSIS
\fIssh(\fBuser\fR as string, 
\fBpassword\fR as string, 
\fBendpoint\fR as string = "127.0.0.1", 
\fBport\fR as integer = 22, 
\fBplink\fR as string = "plink", 
\fBdebug\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Create a new remote linux ssh session
.PP
.SH OPTIONS
.PP
\fBuser$\fB \fR\- -. 
.PP
.PP
\fBpassword$\fB \fR\- -. 
.PP
.PP
\fBendpoint$\fB \fR\- -. 
.PP
.PP
\fBport%\fB \fR\- -. 
.PP
.PP
\fBplink\fB \fR\- -. 
.PP
.SH SEE ALSO
bash
.SH FILES
.PP
Darwinism.dll
.PP
